[tool.poetry]
name = "telegram-webapp-auth"
version = "1.0.1"
description = "Python package that implements Telegram Web authentication algorithm."
authors = ["Dmitry Vasiliev <contact.vasiliev.dmitry@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/telegram-webapp-auth/"
repository = "https://github.com/swimmwatch/telegram-webapp-auth"
keywords = ["Telegram", "Telegram Bot"]
packages = [{include = "telegram_webapp_auth"}]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
mypy = "^1.0.1"
flake8 = "5.0.4"
black = ">=23.1,<25.0"
lazydocs = "^0.4.8"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
show_error_codes = true

[tool.black]
target-version = ["py38"]
line_length = 120